version: '3.8'
services:
#####---------------------kafka_Service--------------######### 
 
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 

#####---------------------Proxy_Service--------------######### 
  
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - product_service
      - order_service
      - user_service
    ports:
      - "80:80"

#####---------------------Order_Service--------------#########      
  
  order_service:
    build:
       context: ./Order_service
    restart: always
    depends_on:
      - broker
    ports:
       - "3003:3003"     
    deploy:
      mode: replicated
      replicas: 1 
                                                                                           
#####---------------------Product_Service--------------######### 
  product_service:
     build:
       context: ./Product_service
     restart: always
     depends_on:
      - "kafka"
     ports:
       - "3001:3001"  
     deploy:
      mode: replicated
      replicas: 1   

#####---------------------User_Service--------------######### 
  user_service:
     build:
       context: ./User_service
     restart: always
     depends_on:
      - "kafka"
     ports:
       - "3000:3000"  
     deploy:
      mode: replicated
      replicas: 1    

