version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    deploy:
       mode: global  
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 

  nginx-proxy:
    build:
      image: irshit033/proxy:latest
    depends_on:
      - product_service
      - order_service
      - user_service
    ports:
      - "80:80"
    deploy:
         mode: replicated
         replicas: 1

  order-service:
      image: irshit033/order:latest
      depends_on:
      - "kafka"
      deploy:
         mode: replicated
         replicas: 1
  
  product-service:
      image: irshit033/product:latest
      deploy:
         mode: replicated
         replicas: 1

  user-service:
      image: irshit033/user:latest
      depends_on:
      - "kafka"
      deploy:
         mode: replicated
         replicas: 1       
