name: Order_Service

on:

  push:
    branches:
    - main
    paths:
    - server/Product_service/**

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      working-directory: ./server/Prder_service
      run: go build -v ./...
